export const ADD_ROUTE = "ADD_ROUTE";
export const CALCULATE_ROUTE = "CALCULATE_ROUTE";
export const FAILED_ROUTE = "FAILED_ROUTE";
export const GET_DIRECTIONS = "GET_DIRECTIONS";
export const UPDATE_ORIGIN = "UPDATE_ORIGIN";
export const UPDATE_DESTINATION = "UPDATE_DESTINATION";
export const DELETE_ROUTE = "DELETE_ROUTE";
export const GET_WAYPOINTS = "GET_WAYPOINTS";